flask_blog_portfolio/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, FileField
from wtforms.validators import DataRequired
from wtforms import SelectField
from flask_wtf.file import FileAllowed


class PostForm(FlaskForm):
    title = StringField('Заголовок', validators=[DataRequired()])
    content = TextAreaField('Текст', validators=[DataRequired()])
    picture = FileField('Приложите фото к посту', validators=[FileAllowed(['jpg', 'png'])])
    submit = SubmitField('Просмотр')


class CommentForm(FlaskForm):
    comment = StringField('Комментарий', validators=[DataRequired()])


class LikeForm(FlaskForm):
    submit = SubmitField('Создать')

flask_blog_portfolio/posts/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
from flask_login import current_user, login_required
from flask_blog_portfolio import db
from flask_blog_portfolio.models import Post, Comment, Like, Category, Hashtag
from flask_blog_portfolio.posts.forms import PostForm, CommentForm, LikeForm
from flask_blog_portfolio.users.utils import save_picture

posts = Blueprint('posts', __name__)


@posts.route("/allpost", methods=['GET', 'POST'])
@login_required
def allpost(post_id=None):
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=6)
    like_form = LikeForm()
    like_count = Like.query.filter_by(post_id=post_id).count()

    return render_template('allpost.html', posts=posts, like_form=like_form, like_count=like_count)


@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    categories = Category.query.all()
    hashtags = Hashtag.query.all()
    form = PostForm()
    picture_name = None

    if form.validate_on_submit():
        if form.picture.data:
            picture_name = save_picture(form.picture.data)

        post = Post(title=form.title.data, content=form.content.data, author=current_user, image_file=picture_name,
                    category_id=request.form['category'])

        hashtags_id = request.form.getlist('hashtags[]')
        hashtags_new = request.form.getlist('hashtags_new[]')

        for i in range(len(hashtags_new)):
            if len(hashtags_new[i]) > 0:
                hastag = Hashtag(name=hashtags_new[i])
                db.session.add(hastag)
                db.session.commit()
                hashtags_id.append(hastag.id)

        for i in hashtags_id:
            hash = Hashtag.query.filter_by(id=int(i)).all()
            post.hashtags.extend(hash)

        db.session.add(post)
        db.session.commit()

        flash('Ваш пост создан!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    return render_template('create_post.html', title='Новая статья', form=form, image_file=picture_name,
                           legend='Новая статья', categories=categories, hashtags=hashtags)


@posts.route("/post/<int:post_id>", methods=['GET', 'POST'])
def post(post_id):
    post = Post.query.get_or_404(post_id)
    like_form = LikeForm()
    like_count = Like.query.filter_by(post_id=post_id).count()

    form = CommentForm()
    if form.validate_on_submit():
        comment = Comment(body=form.comment.data, post_id=post_id, username=current_user.username)
        db.session.add(comment)
        db.session.commit()
        flash('Ваш комментарий добавлен!', 'success')
        return redirect(f'/post/{post_id}')

    return render_template('post.html', title=post.title, post=post, form=form, like_form=like_form,
                           like_count=like_count)


@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data

        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            post.image_file = picture_file

        db.session.commit()
        flash('Ваш пост обновлен!', 'success')

        return redirect(url_for('posts.post', post_id=post.id))

    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content

        image_file = url_for('static', filename='posts_pics/' + post.image_file)

    return render_template('create_post.html', title='Обновление поста', image_file=image_file,
                           form=form, legend='Обновление поста')


@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Ваш пост был удален!', 'success')
    return redirect(url_for('posts.allpost'))


@posts.route("/comment/<int:comment_id>/delete", methods=['POST'])
@login_required
def delete_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    if comment.username != current_user.username:
        abort(403)
    db.session.delete(comment)
    db.session.commit()
    flash('Ваш комментарий был удален!', 'success')

    return redirect(url_for('posts.post', post_id=comment.post_id))


@posts.route('/post/<string:post_id>/like', methods=('POST',))
@login_required
def like_post(post_id):
    post = Post.query.get_or_404(post_id)

    if post.author == current_user:
        flash('Вы не можете поставить лайк т.к. пост создали Вы сами', 'warning')
    elif Like.query.filter_by(user_id=current_user.id, post_id=post_id).count():
        Like.query.filter_by(user_id=current_user.id, post_id=post_id).delete()
        db.session.commit()
        flash('Вам больше не нравится этот пост.', 'success')
    else:
        like = Like(user_id=current_user.id, post_id=post_id)
        db.session.add(like)
        db.session.commit()
        flash('Вам нравится этот пост.', 'success')

    return redirect(url_for('posts.post', post_id=post_id))


@posts.route("/favorites", methods=['GET', 'POST'])
@login_required
def favorites():
    posts = Post.query.all()
    like = Like.query.filter_by(user_id=current_user.id).all()
    print(like)
    count = Like.query.filter_by(user_id=current_user.id).count()
    print(count)
    favorite_posts = []
    for post in posts:
        if post.id in like:
            favorite_posts.append(post)
    print(posts)
    print(favorite_posts)

    return render_template('favorites.html', title='Избранное', posts=favorite_posts, like=like, count=count)

flask_blog_portfolio/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from flask_blog_portfolio import db, bcrypt
from flask_blog_portfolio.models import User, Post, Like
from flask_blog_portfolio.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm,
                                              ResetPasswordForm)
from flask_blog_portfolio.posts.forms import LikeForm
from flask_blog_portfolio.users.utils import send_reset_email

from flask_blog_portfolio.users.utils import save_picture

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Ваша учетная запись была создана! Теперь вы можете войти в систему', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('posts.allpost'))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('posts.allpost'))

    else:
        flash('Войти не удалось. Пожалуйста, проверьте электронную почту и пароль', 'внимание')
    return render_template('login.html', title='Авторизация', form=form)


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Ваш аккаунт был обновлен!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
        page = request.args.get('page', 1, type=int)
        user = User.query.filter_by(username=form.username.data).first_or_404()
        posts = Post.query.filter_by(author=user).order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Аккаунт', image_file=image_file, form=form, posts=posts, user=user)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user).order_by(Post.date_posted.desc()).paginate(page=page, per_page=6)
    return render_template('user_posts.html', posts=posts, user=user)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('posts.allposts'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('На почту отправлено письмо с инструкциями по сбросу пароля.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Сброс пароля', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('posts.allpost'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('Это недействительный или просроченный токен', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Ваш пароль был обновлен! Теперь вы можете авторизоваться', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Сброс пароля', form=form)

flask_blog_portfolio/templates/account.html
{% extends "layout.html" %}

{% block body %}
<section class="account">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-3 text-center">
                <div class="media">
                    <img class="rounded-circle img-thumbnail account_img"
                         src="{{ url_for('static', filename='profile_pics/' + current_user.image_file) }}">
                    <div class="media-body">
                        <h2 class="account-heading mt-4">{{ current_user.username }}</h2>
                        <p class="text-secondary">{{ current_user.email }}</p>
                    </div>
                </div>
            </div>
            <div class="col-5">
                <form method="POST" action="" enctype="multipart/form-data">
                    {{ form.hidden_tag() }}
                    <fieldset class="form-group">
                        <legend class="border-bottom mb-4">Личный кабинет</legend>
                        <div class="form-group mb-4">
                            <div class="account_label">
                                {{ form.username.label(class="form-control-label ") }}
                            </div>
                            {% if form.username.errors %}
                            {{ form.username(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                            {% else %}
                            {{ form.username(class="form-control form-control") }}
                            {% endif %}
                        </div>
                        <div class="form-group mb-4">
                            {{ form.email.label(class="form-control-label") }}
                            {% if form.email.errors %}
                            {{ form.email(class="form-control form-control is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                            {% else %}
                            {{ form.email(class="form-control form-control") }}
                            {% endif %}
                        </div>
                        <div class="form-group mb-4">
                            {{ form.picture.label() }}
                            {{ form.picture(class="form-control-file") }}
                            {% if form.picture.errors %}
                            {% for error in form.picture.errors %}
                            <span class="text-danger">{{ error }}</span><br>
                            {% endfor %}
                            {% endif %}
                        </div>
                    </fieldset>
                    <div class="form-group mb-4">
                        {{ form.submit(class="btn btn btn-warning") }}
                    </div>
                </form>
            </div>
        </div>
        <div>
            <div class="list-group w-auto mb-4">

                <h3 class="mb-4">Мои статьи</h3>
                {% for post in posts.items %}
                <div>
                    <div class="list-group-item list-group-item-action d-flex bg-body-secondary bg-opacity-50 account_posts">
                        <a href="{{ url_for('posts.post', post_id=post.id) }}" class="" aria-current="true">
                            <img src="{{ url_for('static', filename='profile_pics/' + post.image_file) }}" alt="twbs"
                                 height="100"
                                 class="flex-shrink-0 account_posts_img">
                        </a>
                        <div class="d-flex gap-2 w-100 justify-content-between p-3">
                            <div>
                                <a href="{{ url_for('posts.post', post_id=post.id) }}">
                                    <h6 class="mb-0 pb-2 fs-5">{{ post.title }}</h6>
                                </a>
                                <p class="mb-0 opacity-75">{{ post.content |truncate(80, False, '...', 0)}}</p>
                            </div>
                            <div class="d-flex flex-column account_posts_btn">
                                <small class="opacity-50 text-nowrap">{{ post.date_posted.strftime('%d %B %Y %I:%M %p')
                                    }}</small>
                                <div class="p-0">
                                    <div>
                                        <a class="btn btn btn-warning btn-sm mt-1 mb-1"
                                           href="{{url_for('posts.update_post', post_id=post.id) }}">Обновить</a>
                                        <button type="button" class="btn btn-danger btn-sm m-1" data-bs-toggle="modal"
                                                data-bs-target="#deleteModal">Удалить
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Modal -->
                <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel"
                     aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h1 class="modal-title fs-5" id="exampleModalLabel">Удалить пост?</h1>
                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                        aria-label="Закрыть"></button>
                            </div>
                            <div class="modal-body">
                                <div class="d-flex gap-2 w-100 p-3 align-items-center">
                                    <div class="account_posts">
                                        <img src="{{ url_for('static', filename='profile_pics/' + post.image_file) }}"
                                             alt="twbs" height="100" class="account_posts_img modal_posts_img">
                                    </div>
                                    <h6 class="mb-2 fs-5">{{ post.title }}</h6>
                                </div>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
                                    Отмена
                                </button>
                                <form action="{{ url_for('posts.delete_post', post_id=post.id) }}"
                                      method="POST">
                                    <input class="btn btn-danger" type="submit" value="Удалить">
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</section>
{% endblock %}

flask_blog_portfolio/templates/layout.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
    {% if title %}
    <title>{% block title %}{% endblock %}</title>
    {% else %}
    <title>Blog</title>
    {% endif %}
</head>
<body>
<div class="container">
    <nav class="navbar navbar-expand-lg bg-body-tertiary fixed-top">
        <div class="container-fluid container">
            <a href="/home" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
                <svg class="bi me-2" width="150" height="30">
                    <use xlink:href="{{ url_for('static', filename='icon/sprite.svg')}}#LOGO 1"></use>
                </svg>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar"
                    aria-controls="offcanvasNavbar">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar"
                 aria-labelledby="offcanvasNavbarLabel">
                <div class="offcanvas-header">
                    <h5 class="offcanvas-title" id="offcanvasNavbarLabel"> <svg class="bi me-2" width="150" height="30">
                    <use xlink:href="{{ url_for('static', filename='icon/sprite.svg')}}#LOGO 1"></use>
                </svg></h5>
                    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                </div>
                <div class="offcanvas-body">
                    <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="/home">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('posts.allpost') }}">Blog</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">About as</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                               aria-expanded="false">
                                Language
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="#">English</a></li>
                                <li><a class="dropdown-item" href="#">Русский</a></li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item" href="#">Тарабарский</a></li>
                            </ul>
                        </li>

                        {% if current_user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-item nav-link navigation-links" href="{{ url_for('posts.new_post') }}"><i class="fa fa-plus"></i>Add post</a>

                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                               aria-expanded="false">Hi, {{ current_user.username }}!
                            </a>
                            <ul class="dropdown-menu">

                                <li><a class="dropdown-item" href="{{ url_for('users.account') }}">Profile</a></li>
                                <li><a class="dropdown-item" href="{{ url_for('posts.new_post') }}">Add post</a></li>
                                <li>
                                    <a class="dropdown-item" href="#">
                                        Favorites posts
                                        <svg class="bi me-2 position-relative" width="25" height="30">
                                            <use xlink:href="../static/icon/sprite.svg#zakladka"></use>
                                            <span class="position-absolute top-10 start-1 translate-middle badge rounded-pill bg-danger">
                                                99+
                                            </span>
                                        </svg>
                                    </a>
                                </li>
                                <li><a class="dropdown-item" href="{{ url_for('users.logout') }}">Logout</a></li>
                            </ul>
                        </li>

                        {% else %}

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                               aria-expanded="false">Login
                            </a>
                            <ul class="dropdown-menu">

                                <li><a class="dropdown-item" href="{{ url_for('users.register') }}">Register</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" href="{{ url_for('users.login') }}">Login</a></li>
                            </ul>
                        </li>

                        {% endif %}

                    </ul>
                </div>
            </div>
        </div>
    </nav>
</div>
{% block search %}
{% endblock %}
{% block body %}
{% endblock %}


<script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js')}}"></script>
</body>
</html>

flask_blog_portfolio/templates/post.html
{% extends "layout.html" %}

{% block body %}
<section>
    <div class="container">
        <div class="d-flex flex-row mb-3">
            <div class="p-2">
                {% for tag in post.hashtags %}
                <span class="btn btn-warning text-light post_tag">{{ tag.name}}</span>
                {% endfor %}
            </div>
        </div>
        <div class="d-flex flex-row mb-3">
            <div class="p-2"><h4 class="post_title">{{ post.title }}</h4></div>
        </div>
        <div class="d-flex flex-row mb-3">
            <div class="p-2"><img class="post_author"
                                  src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
            </div>
            <div class="p-2"><a class="post_author_name"
                                href="{{ url_for('users.user_posts', username=post.author.username) }}"
                                style="margin: 0 auto">{{ post.author.username }}</a></div>
            <div class="p-2"><small>Опубликовано {{ post.date_posted.strftime('%A, %d %B %Y %I:%M %p') }}</small></div>

            <div class="p-2">
                <form action="{{ url_for('posts.like_post', post_id=post.id) }}" method="post">
                    {{ like_form.hidden_tag() }}
                    <button type="submit"
                            style="border: none; background-color: #FFFFFF;">
                        <img style="width: 32px;" src="{{ url_for('static', filename='image/like.svg') }}" alt="...">
                        {{ like_count if like_count > 0 }}
                    </button>
                </form>
            </div>
        </div>
        {% if post.image_file != 'default.png' %}
        <div class="d-flex flex-row mb-3">
            <img class="post_img" src="{{ url_for('static', filename='profile_pics/' + post.image_file) }}">
        </div>
        {% endif %}
        <div class="d-flex flex-row mb-3">
            <div class="p-2">{{ post.content }}</div>
        </div>
        <div class="d-flex flex-row flex-row-reverse">
            <div class="p-2">
                <div class="card-footer" style="font-size: 20px;"><a class="btn btn-warning text-light btn-sm mt-1 mb-1"
                                                                     href="{{url_for('posts.allpost') }}">Назад к
                    постам</a>
                    {% if post.author == current_user %}
                    <a class="btn btn-warning text-light btn-sm mt-1 mb-1"
                       href="{{url_for('posts.update_post', post_id=post.id) }}">Редактировать</a>
                    <a class="btn btn-warning text-light btn-sm mt-1 mb-1" href="{{url_for('posts.allpost') }}">Сохранить</a>
                    <button type="button" class="btn btn-danger btn-sm m-1" data-bs-toggle="modal"
                            data-bs-target="#deleteModal">Удалить
                    </button>
                    {% endif %}
                </div>
            </div>
        </div>

        <!-- Modal -->
        <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel"
             aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h1 class="modal-title fs-5" id="exampleModalLabel">Удалить пост?</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        ...
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
                        <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
                            <input class="btn btn-danger" type="submit" value="Удалить">
                        </form>
                    </div>
                </div>
            </div>
        </div>


        <div id="content">
            <!-- insert the page content here -->
            <h2 class="post_title_comment">Оставьте комментарий</h2>
            <form action="" method="post">
                {{ form.hidden_tag() }}
                <div class="form_settings">
                    <div class="d-flex flex-row mb-3">
                        <textarea class="post_comment_textarea" placeholder="Ваш комментарий" name="comment"
                                  rows="3"></textarea>
                        {% if form.comment.errors %}
                        {% for error in form.comment.errors %}
                        <p style="color: red">{{ error }}</p>
                        {% endfor %}
                        {% endif %}
                    </div>
                    <div class="d-flex flex-row flex-row-reverse">
                        <input class="btn btn-warning text-light btn-sm mt-1 mb-1" type="submit" name="submit"
                               value="Сохранить">
                    </div>
                </div>
            </form>
        </div>

        {% if post.comments | length != 0 %}

        <h2 class="post_title">Комментарии: </h2>
        <p>{% for comment in post.comments | reverse %}
        <div class="post_comment shadow-sm">
            <div class="d-flex flex-row">
                <p style="font-size: 14px;">{{ comment.body }}</p>
            </div>
            <div class="d-flex flex-row">
                <span class="flex-grow-1"><small>Автор: {{ comment.username }}</small></span>
                <span class="post_comment_footer"><small>Дата: {{ comment.timestamp.strftime('%A, %d %B %Y %I:%M %p') }}</small></span>

                {% if comment.username == current_user.username %}
                <form action="{{ url_for('posts.delete_comment', comment_id=comment.id) }}" method="POST" class="post_comment_footer">
                    <input class="btn btn-warning text-light btn-sm mt-1 mb-1 post_comment_btn" type="submit" value="Удалить">
                </form>
            </div>
        </div>
        {% endif %}
        <hr>
        {% endfor %}
        {% endif %}

    </div>

</section>
{% endblock %}